name: üõçÔ∏è Fetch ‚öôÔ∏è Weekly üì± (aarch64_arm64_v8a_Android) Package üì¶üóÑÔ∏è
#MAX_RUNTIME:  
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *" #  06:45 AM NPT Mrng Every Day
  
env:
  GITHUB_TOKEN: ${{ secrets.TOOLPACKS }}
  
jobs:
#------------------------------------------------------------------------------------#
#------------------------------------------------------------------------------------#
  fetch-binaries:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:        
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: main

      - name: Debloat Runner
        run: |
          #Presets
          set -x ; set +e
          #--------------#
          #12.0 GB  
          #This is needed, this is the ndk
          #sudo rm /usr/local/lib/android -rf 2>/dev/null
          #8.2 GB
          sudo rm /opt/hostedtoolcache/CodeQL -rf 2>/dev/null
          #5.0 GB
          sudo rm /usr/local/.ghcup -rf 2>/dev/null
          #2.0 GB
          sudo rm /usr/share/dotnet -rf 2>/dev/null
          #1.7 GB
          sudo rm /usr/share/swift -rf 2>/dev/null
          #1.1 GB
          #sudo rm /usr/local/lib/node_modules -rf 2>/dev/null
          #1.0 GB
          sudo rm /usr/local/share/powershell -rf 2>/dev/null
          #500 MB
          sudo rm /usr/local/lib/heroku -rf 2>/dev/null
        continue-on-error: true
        
      - name: Install CoreUtils & Deps
        run: |
          #Presets
          set -x ; set +e
          #--------------#
          sudo apt-get update -y
          sudo apt-get install automake b3sum build-essential ca-certificates ccache lzip jq make musl musl-dev musl-tools p7zip-full wget -y
          sudo apt-get install -y --no-install-recommends autoconf automake autopoint binutils bison build-essential ca-certificates flex file jq patch patchelf pkg-config python3-pip qemu-user-static wget 
          #Bin Utils
          sudo apt install binutils-aarch64-linux-gnu -y
          #libpcap
          sudo apt install 'libpcap*' -y
          sudo apt install 'nmap' -y
        continue-on-error: true
        
      - name: Install PythonUtils & Deps
        run: |
          #Presets
          set -x ; set +e
          #--------------#
          sudo apt-get install libxcb1-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev xcb -y
          pip install ansi2txt
          pip install scons
          pip install staticx
          pip install pyinstaller
          pip install py2static
          pip install typer
        continue-on-error: true
        
      - name: Install CargoUtils & Deps
        run: |
          #Presets
          set -x ; set +e
          #--------------#
          cargo install cross --git "https://github.com/cross-rs/cross"
        continue-on-error: true

    ##Needed until gh runners updates go version: https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md
    ## It helps to be on bleeding edge anyway
      - name: Install/Update golang
        run: |
          #Presets
          set -x ; set +e
          #--------------#
          echo "yes" | bash <(curl -qfsSL "https://git.io/go-installer")
          source "$HOME/.bashrc"
        continue-on-error: true

      - name: Install Addons
        run: |
          #Presets
          set -x ; set +e
          #--------------#
          #eget
          curl -qfsSL "https://zyedidia.github.io/eget.sh" | bash
          sudo mv ./eget* "/usr/local/bin/eget"
          sudo chmod +xwr "/usr/local/bin/eget"
        continue-on-error: true

      - name: Install Crystal
        run: |
          #https://crystal-lang.org/install/on_ubuntu/
          curl -fsSL https://crystal-lang.org/install.sh | sudo bash
        continue-on-error: true

      - name: Install 7z
        run: |
          #Presets
          set -x ; set +e
          #--------------#
          cd $(mktemp -d) && curl -qfsSLJO "https://www.7-zip.org/$(curl -qfsSL "https://www.7-zip.org/download.html" | grep -o 'href="[^"]*"' | sed 's/href="//' | grep 'linux-x64.tar.xz' | sed 's/"$//' | sort | tail -n 1)"
          find . -type f -name '*.xz' -exec tar -xf {} \;
          #sudo rm $(which 7z) 2>/dev/null ; sudo rm $(which 7z) 2>/dev/null
          sudo find . -type f -name '7zzs' ! -name '*.xz' -exec cp {} "/usr/local/bin/7z" \;
          sudo chmod +xwr "/usr/local/bin/7z"
          sudo find . -type f -name '7zzs' ! -name '*.xz' -exec cp {} "/usr/bin/7z" \;
          sudo chmod +xwr "/usr/bin/7z"
          7z -h
        continue-on-error: true

      - name: Install upX
        run: |
          cd $(mktemp -d) && curl -qfLJO "$(curl -qfsSL https://api.github.com/repos/upx/upx/releases/latest | jq -r '.assets[].browser_download_url' | grep -i 'amd64_linux')"
          find . -type f -name '*tar*' -exec tar -xvf {} \;
          sudo find . -type f -name 'upx' -exec mv {} "$(which upx)" \;  
        continue-on-error: true
#------------------------------------------------------------------------------------#
#Fetch: Only those that are known to work (have been tested)
#     : Must not exist at : https://github.com/Azathothas/Toolpacks/tree/main/Info/Packages/Termux


     ##bottom
      - name: Build bottom (Native)
        run: |
          #Presets
          set -x ; set +e
          #--------------#
          #Get Source
          pushd "$(mktemp -d)" && git clone "https://github.com/ClementTsang/bottom" && cd "./bottom"
          #android29 --> Android 10 or later
          export TARGET="aarch64-linux-android" ; export RUSTFLAGS="-C linker=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android29-clang -C ar=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar" 
          rustup target add "$TARGET"
          #Config
          sed '/^\[profile\.release\]/,/^$/d' -i "./Cargo.toml"  
          echo -e '\n[profile.release]\nstrip = true\nopt-level = "z"\nlto = true' >> "./Cargo.toml"
          #Build
          cargo build --target $TARGET --release --no-default-features 
          #move
          mv "./target/$TARGET/release/btm" "$GITHUB_WORKSPACE/main/aarch64_arm64_v8a_Android/btm" ; popd
        continue-on-error: true

     ##eget
      - name: Build eget (Native)
        run: |
          #Presets
          set -x ; set +e
          #--------------#
          #Get Source
          pushd $(mktemp -d) && git clone "https://github.com/zyedidia/eget" && cd eget
          # android 29 --> Android 10.0 or Later
          # ANDROID_NDK = /usr/local/lib/android/sdk/ndk/
          export CC="$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android29-clang"
          export CXX="$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android29-clang++"
          #Compile
          # CGO_ENABLED must be enabled to use android native libs, else things like dns etc won't work
          # Binaries compiled this way are always dynamically linked to /system/bin/linker64
          GOOS=android GOARCH=arm64 CGO_ENABLED=1 go build -v -ldflags="-s -w"
          #Move
          mv "./eget" "$GITHUB_WORKSPACE/main/aarch64_arm64_v8a_Android/eget" ; popd
          #Clean Cache
          go clean -cache -fuzzcache -modcache -testcache
        continue-on-error: true

     ##filebrowser
      - name: Download filebrowser
        run: |
          #Presets
          set -x ; set +e
          #--------------#
          eget "filebrowser/filebrowser" --asset "arm64" --asset "linux" --to "$GITHUB_WORKSPACE/main/aarch64_arm64_v8a_Android/filebrowser"
        continue-on-error: true

    ##miniserve
      - name: Download miniserve
        run: |
          #Presets
          set -x ; set +e
          #--------------#
          eget "svenstaro/miniserve" --asset "aarch64" --asset "linux" --asset "musl" --to "$GITHUB_WORKSPACE/main/aarch64_arm64_v8a_Android/miniserve"
        continue-on-error: true

     ##pspy
      - name: Build pspy (Native)
        run: |
          #Presets
          set -x ; set +e
          #--------------#
          #Get Source
          pushd $(mktemp -d) && git clone "https://github.com/DominicBreuker/pspy" && cd "./pspy"
          # android 29 --> Android 10.0 or Later
          # ANDROID_NDK = /usr/local/lib/android/sdk/ndk/
          export CC="$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android29-clang"
          export CXX="$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android29-clang++"
          #Compile
          # CGO_ENABLED must be enabled to use android native libs, else things like dns etc won't work
          # Binaries compiled this way are always dynamically linked to /system/bin/linker64
          GOOS=android GOARCH=arm64 CGO_ENABLED=1 go build -v -ldflags="-s -w"
          #Move
          mv "./pspy" "$GITHUB_WORKSPACE/main/aarch64_arm64_v8a_Android/pspy" ; popd
          #Clean Cache
          go clean -cache -fuzzcache -modcache -testcache
        continue-on-error: true
        
     ##static-web-server
      - name: Download static-web-server
        run: |
          #Presets
          set -x ; set +e
          #--------------#
          eget "static-web-server/static-web-server" --asset "aarch64" --asset "android" --to "$GITHUB_WORKSPACE/main/aarch64_arm64_v8a_Android/static-web-server"
        continue-on-error: true

    ##TailScale
      - name: Download TailScale
        run: |
          #Presets
          set -x ; set +e
          #--------------#
          #tailscale
          eget "https://github.com/Azathothas/Static-Binaries/raw/main/tailscale/tailscale_aarch64_arm64_Linux" --to "$GITHUB_WORKSPACE/main/aarch64_arm64_v8a_Android/tailscale"
          #tailscale_merged
          eget "https://github.com/Azathothas/Static-Binaries/raw/main/tailscale/tailscale_merged_aarch64_arm64_Linux" --to "$GITHUB_WORKSPACE/main/aarch64_arm64_v8a_Android/tailscale_merged"
          #tailscaled
          eget "https://github.com/Azathothas/Static-Binaries/raw/main/tailscale/tailscaled_aarch64_arm64_Linux" --to "$GITHUB_WORKSPACE/main/aarch64_arm64_v8a_Android/tailscaled"
        continue-on-error: true
     ##Build
      - name: Build TailScale (Native)
        run: |
          #Presets
          set -x ; set +e
          #--------------#
          #Get Source
          cd $(mktemp -d) && curl -LOJ $(curl -s https://api.github.com/repos/tailscale/tailscale/releases/latest | jq -r '.zipball_url')
          find . -type f -name '*.zip*' -exec unzip -o {} \;
          cd $(find . -maxdepth 1 -type d | grep -v '^.$')
          # android 29 --> Android 10.0 or Later
          # ANDROID_NDK = /usr/local/lib/android/sdk/ndk/
          export CC="$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android29-clang"
          export CXX="$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android29-clang++"
          #Deps
          go env -w GO111MODULE=on
          #Compile
          # CGO_ENABLED must be enabled to use android native libs, else things like dns etc won't work
          # Binaries compiled this way are always dynamically linked to /system/bin/linker64
          #TailScale
          GOOS=android GOARCH=arm64 CGO_ENABLED=1 go build -v -ldflags="-s -w" "./cmd/tailscale"
          #TailScaled
          GOOS=android GOARCH=arm64 CGO_ENABLED=1 go build -v -ldflags="-s -w" "./cmd/tailscaled"
          #TailScale merged: https://tailscale.com/kb/1207/small-tailscale/
          GOOS=android GOARCH=arm64 CGO_ENABLED=1 go build -o "./tailscale.combined" -v -ldflags="-s -w" -tags "ts_omit_aws,ts_omit_bird,ts_omit_tap,ts_omit_kube,ts_include_cli" "./cmd/tailscaled"
          #Move
          mv "./tailscale" "$GITHUB_WORKSPACE/main/aarch64_arm64_v8a_Android/tailscale_dynamic_native"
          mv "./tailscaled" "$GITHUB_WORKSPACE/main/aarch64_arm64_v8a_Android/tailscaled_dynamic_native"
          mv "./tailscale.combined" "$GITHUB_WORKSPACE/main/aarch64_arm64_v8a_Android/tailscale_merged_dynamic_native"
          #Clean Cache
          go clean -cache -fuzzcache -modcache -testcache
        continue-on-error: true

#------------------------------------------------------------------------------------#
      - name: Strip || Cleanup
        run: |
           #Presets
           set -x ; set +e
           #--------------#
           cd "$GITHUB_WORKSPACE/main/aarch64_arm64_v8a_Android"
           find "$GITHUB_WORKSPACE/main/aarch64_arm64_v8a_Android/" -maxdepth 1 -type f -exec aarch64-linux-gnu-objcopy --preserve-dates --verbose --strip-all {} \; 2>/dev/null
           # Strip && Rename anything with *_amd*
           # find "$GITHUB_WORKSPACE/main/aarch64_arm64_v8a_Android" -type f -name '*_Linux' -exec sh -c 'newname=$(echo "$1" | sed "s/_amd_aarch64_arm64_v8a_Android_Linux//"); mv "$1" "$newname"' sh {} \;
        continue-on-error: true

      - name: Update README.md
        run: |
           #Presets
           set -x ; set +e
           #--------------#
           cd "$GITHUB_WORKSPACE/main"
           echo -e "" > "./aarch64_arm64_v8a_Android/README.md"
           echo '---' >> "./aarch64_arm64_v8a_Android/README.md"
           echo '```console' >> "./aarch64_arm64_v8a_Android/README.md"
           echo -e "" >> "./aarch64_arm64_v8a_Android/README.md"
           echo -e "--> METATDATA" >> "./aarch64_arm64_v8a_Android/README.md"
           /bin/bash -c 'PS4="$ "; file ./aarch64_arm64_v8a_Android/* | grep -v '.txt' ' &>> "./aarch64_arm64_v8a_Android/README.md"
           echo -e "" >> "./aarch64_arm64_v8a_Android/README.md"
           echo -e "--> SHA256SUM" >> "./aarch64_arm64_v8a_Android/README.md"
           /bin/bash -c 'PS4="$ ";sha256sum ./aarch64_arm64_v8a_Android/* | grep -v '.txt' ' &>> "./aarch64_arm64_v8a_Android/README.md" 
           echo -e '```\n' >> "./aarch64_arm64_v8a_Android/README.md"
           echo -e "" >> "./aarch64_arm64_v8a_Android/README.md"
           echo '---' >> "./aarch64_arm64_v8a_Android/README.md"
           echo -e "" >> "./aarch64_arm64_v8a_Android/README.md"
           echo '- #### Sizes' >> "./aarch64_arm64_v8a_Android/README.md"
           echo -e "" >> "./aarch64_arm64_v8a_Android/README.md"
           echo '```console' >> "./aarch64_arm64_v8a_Android/README.md"
           /bin/bash -c 'PS4="$ ";ls -lh ./aarch64_arm64_v8a_Android/* | grep -v '.txt' | awk "{print \$5, \$9}" | column -t' &>> "./aarch64_arm64_v8a_Android/README.md"
           echo -e "\n[+] Total Size: $(du -h ./aarch64_arm64_v8a_Android | awk '{print $1}')\n"
           echo '```' >> "./aarch64_arm64_v8a_Android/README.md"   
           echo -e "" >> "./aarch64_arm64_v8a_Android/README.md"
           echo '---' >> "./aarch64_arm64_v8a_Android/README.md"
           echo -e "" >> "./aarch64_arm64_v8a_Android/README.md"
        continue-on-error: true

      - name: Git Pull
        run: |
           cd "$GITHUB_WORKSPACE/main" && git pull origin main
        continue-on-error: true

      - name: Get DateTime
        run: |
          # Date Time
          NEPALI_TIME=$(TZ='Asia/Kathmandu' date +'%Y-%m-%d (%I:%M:%S %p)')
          echo "NEPALI_TIME=$NEPALI_TIME" >> $GITHUB_ENV
          
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: ./main        
          commit_user_name: Azathothas # defaults to "github-actions[bot]"
          commit_user_email: AjamX101@gmail.com # defaults to "41898282+github-actions[bot]@users.noreply.github.com"
          commit_message: "‚úÖ üõçÔ∏è Fetch ‚öôÔ∏è Weekly (aarch64_arm64_v8a_Android) Package üì¶üóÑÔ∏è <-- ${{ env.NEPALI_TIME }} ‚åö"
          #push_options: '--force'
